// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "rEZsX0wHtHBDzfnD7efTeersQ8oMbX8xUOy4Lci2PnUthZW0lOeQ0Cv7K7QAVklJZDA9Ew";
}
}
}

